--CREATE TABLE IF NOT EXISTS `games` (
--  `id` bigint(20) NOT NULL AUTO_INCREMENT,
--  `playerName` varchar(255) DEFAULT NOT NULL,
--  `gameDate` datetime(6) DEFAULT NOT NULL
--  PRIMARY KEY (`id`)
--) ENGINE=InnoDB
--DEFAULT CHARSET=utf8;
--
--CREATE TABLE IF NOT EXISTS `gameRounds` (
--  `id` bigint(20) NOT NULL AUTO_INCREMENT,
--  `gameId` bigint(20) NOT NULL AUTO_INCREMENT,
--  `playerChoice` varchar(255) DEFAULT NOT NULL,
--  `npcChoice` varchar(255) DEFAULT NOT NULL,
--  PRIMARY KEY (`id`),
--  KEY `gameId` (`gameId`),
--  CONSTRAINT `rounds_ibfk_1` FOREIGN KEY (`gameId`) REFERENCES `games` (`id`)
--) ENGINE=InnoDB;
--DEFAULT CHARSET=utf8;
--
--DELETE FROM `games`;
--DELETE FROM `gameRounds`;